name: Testes de API

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  teste-das-apis:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
    - name: Setup do Node.js
      uses: actions/setup-node@v2.1.1
    - name: Instalar as dependências do projeto
      run: npm ci
    - name: Executar o container docker do ServeRest
      run: docker run -d -p 3000:3000 paulogoncalvesbh/serverest:latest
    - name: Executar os testes de API
      run: npm test